        -- CHATLIEU --
-- SELECT 
SELECT * FROM CHATLIEU

-- XÓA CHẤT LIỆU
DELETE FROM CHATLIEU WHERE MACL = N'PP' 

--SỬA CHẤT LIỆU
UPDATE CHATLIEU SET TENCL = N'PHÓT PHO 123' WHERE MACL = N'PP'

-- THÊM CHẤT LIỆU
INSERT CHATLIEU (MACL, TENCL)
VALUES (N'PP', N'PHÓT PHO')

        -- KHACHHANG --
-- SELECT 
SELECT * FROM KHACHHANG

-- XÓA KHÁCH HÀNG
DELETE FROM KHACHHANG WHERE MAKH = N'KH01' 

--SỬA KHÁCH HÀNG
UPDATE KHACHHANG SET GIOITINH = N'Nam' WHERE MAKH = N'KH01'

-- THÊM KHÁCH HÀNG
INSERT KHACHHANG (MAKH, TENKH, GIOITINH, NGAYSINH, DIACHI, MIEN, DIENTHOAI, EMAIL)
VALUES (N'KH13', N'TRẦN THANH DUY',N'Nam', N'2001-12-12',N'123 LÝ THÁI TỔ', N'TRUNG',N'0879675843',N'tranthanhduy@gmail,.com')

        -- NHANVIEN --
-- SELECT 
SELECT * FROM NHANVIEN

-- XÓA NHÂN VIÊN
DELETE FROM NHANVIEN WHERE MANV = N'NV01' 

--SỬA NHÂN VIÊN
UPDATE NHANVIEN SET GIOITINH = N'Nam' WHERE MANV = N'NV01'

-- THÊM NHÂN VIÊN
INSERT NHANVIEN (MANV, TENNV, MACV, GIOITINH, NGAYSINH, DIACHI, DANTOC, DIENTHOAI, EMAIL, LUONG)
VALUES (N'MANV',N'TENNV',N'MACV',N'GIOITINH',N'NGAYSINH',N'DIACHI', N'DANTOC',N'DIENTHOAI',N'EMAIL',N'LUONG')

