-- STORE PROCEDURE --
-- KIỂM TRA CÓ TỒN TẠI MÃ KHÁCH HÀNG ĐÓ HAY KHÔNG
CREATE PROCEDURE SP_TIMMAKH (@MAKH NVARCHAR(10))
AS
BEGIN
    IF EXISTS (SELECT * FROM KHACHHANG WHERE @MAKH = MAKH)
    BEGIN
        RAISERROR (N'MÃ KHÁCH HÀNG NÀY ĐÃ TỒN TẠI',15,1)
        RETURN 
    END
    ELSE
    BEGIN
        IF EXISTS (SELECT * FROM LINK.QUANLYBANHANG.DBO.KHACHHANG WHERE @MAKH = MAKH)
        BEGIN
            RAISERROR (N'MÃ KHÁCH HÀNG NÀY ĐÃ TỒN TẠI',15,1)
            RETURN
        END
    END
END
EXEC SP_TIMMAKH N'KH21'
GO

-- KIỂM TRA MÃ NHÂN VIÊN ĐÃ TỒN TẠI HAY CHƯA
CREATE PROCEDURE SP_TIMMANV (@MANV NVARCHAR(10))
AS
BEGIN
    IF EXISTS (SELECT * FROM NHANVIEN WHERE @MANV = MANV)
    BEGIN
        RAISERROR (N'MÃ NHÂN VIÊN NÀY ĐÃ TỒN TẠI',15,1)
        RETURN 
    END
    ELSE
    BEGIN
        IF EXISTS (SELECT * FROM LINK.QUANLYBANHANG.DBO.NHANVIEN WHERE @MANV = MANV)
        BEGIN
            RAISERROR (N'MÃ NHÂN VIÊN NÀY ĐÃ TỒN TẠI',15,1)
            RETURN
        END
    END
END
EXEC SP_TIMMANV N'NV22'
GO


-- KIỂM TRA MÃ CHẤT LIỆU ĐÃ TỒN TẠI HAY CHƯA
CREATE PROCEDURE SP_TIMMACL (@MACL NVARCHAR(10))
AS
BEGIN
    IF EXISTS (SELECT * FROM CHATLIEU WHERE @MACL = MACL)
    BEGIN
        RAISERROR (N'MÃ CHẤT LIỆU NÀY ĐÃ TỒN TẠI',15,1)
        RETURN 
    END
    ELSE
    BEGIN
        IF EXISTS (SELECT * FROM LINK.QUANLYBANHANG.DBO.CHATLIEU WHERE @MACL = MACL)
        BEGIN
            RAISERROR (N'MÃ CHẤT LIỆU NÀY ĐÃ TỒN TẠI',15,1)
            RETURN
        END
    END
END
EXEC SP_TIMMACL N'B'
GO


-- KIỂM TRA MÃ HÓA ĐƠN BÁN ĐÃ TỒN TẠI HAY CHƯA
CREATE PROCEDURE SP_TIMMAHDB (@MAHD NVARCHAR(10))
AS
BEGIN
    IF EXISTS (SELECT * FROM HOADONBAN WHERE @MAHD = MAHD)
    BEGIN
        RAISERROR (N'MÃ HÓA ĐƠN BÁN NÀY ĐÃ TỒN TẠI',15,1)
        RETURN 
    END
    ELSE
    BEGIN
        IF EXISTS (SELECT * FROM LINK.QUANLYBANHANG.DBO.HOADONBAN WHERE @MAHD = MAHD)
        BEGIN
            RAISERROR (N'MÃ HÓA ĐƠN BÁN NÀY ĐÃ TỒN TẠI',15,1)
            RETURN
        END
    END
END
EXEC SP_TIMMAHDB N'HD01'
GO

-- KIỂM TRA MÃ CHỨC VỤ ĐÃ TỒN TẠI HAY CHƯA
CREATE PROCEDURE SP_TIMMACV (@MACV NVARCHAR(10))
AS
BEGIN
    IF EXISTS (SELECT * FROM CHUCVU WHERE @MACV = MACV)
    BEGIN
        RAISERROR (N'MÃ CHỨC VỤ NÀY ĐÃ TỒN TẠI',15,1)
        RETURN 
    END
    ELSE
    BEGIN
        IF EXISTS (SELECT * FROM LINK.QUANLYBANHANG.DBO.CHUCVU WHERE @MACV = MACV)
        BEGIN
            RAISERROR (N'MÃ CHỨC VỤ NÀY ĐÃ TỒN TẠI',15,1)
            RETURN
        END
    END
END
EXEC SP_TIMMACV N'CV1'
GO

--LẤY THÔNG TIN CỦA NHÂN VIÊN BÁN HÓA ĐƠN ĐÓ
CREATE PROCEDURE SP_TTNHANVIEN (@MANV NVARCHAR(10))
AS
BEGIN
    IF EXISTS (SELECT * FROM LINK.QUANLYBANHANG.DBO.NHANVIEN WHERE @MANV = MANV)
    BEGIN
        SELECT H.MAHD, N.MANV, N.TENNV, NGAYSINH, GIOITINH, DIENTHOAI, H.TONGTIEN
        FROM LINK.QUANLYBANHANG.DBO.NHANVIEN AS N, LINK.QUANLYBANHANG.DBO.HOADONBAN AS H
        WHERE H.MANV = N.MANV AND @MANV = N.MANV
    END
END
EXEC SP_TTNHANVIEN 'NV01'