----- TRIGGER THÔNG BÁO INSERT THÀNH CÔNG -----
--1. CHATLIEU
CREATE TRIGGER TG_THEMTC_CHATLIEU ON CHATLIEU
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM CHẤT LIỆU THÀNH CÔNG')
END
GO

--2. CHUCVU
CREATE TRIGGER TG_THEMTC_CHUCVU ON CHUCVU
FOR INSERT 
AS
BEGIN
    PRINT (N'THÊM CHỨC VỤ THÀNH CÔNG')
END
GO

--3. CTHDB
CREATE TRIGGER TG_THEMTC_CTHDB ON CTHDB
FOR INSERT
AS
BEGIN
    PRINT(N'THÊM CHI TIẾT HÓA ĐƠN THÀNH CÔNG')
END
GO

--4. HANG
CREATE TRIGGER TG_THEMTC_HANG ON HANG
FOR INSERT
AS 
BEGIN
    PRINT(N'THÊM HÀNG THÀNH CÔNG')
END
GO

--5. HOADONBAN
CREATE TRIGGER TG_THEMTC_HOADONBAN ON HOADONBAN
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM HÓA ĐƠN BÁN THÀNH CÔNG')
END
GO

--6. HTTT
CREATE TRIGGER TG_THENTC_HTTT ON HTTT
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM HÌNH THỨC THANH TOÁN THÀNH CÔNG')
END
GO

--7. KHACHHANG
CREATE TRIGGER TG_THEMTC_KHACHHANG ON KHACHHANG
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM KHÁCH HÀNG THÀNH CÔNG')
END
GO

--8. LICHSUDONGIA
CREATE TRIGGER TG_THEMTC_LICHSUDONGIA ON LICHSUDONGIA
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM LỊCH SỬ ĐƠN GIÁ THÀNH CÔNG')
END
GO

--9. LICHSUNHAPHANG
CREATE TRIGGER TG_THEMTC_LICHSUNHAPHANG ON LICHSUNHAPHANG
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM LỊCH SỬ NHẬP HÀNG THÀNH CÔNG')
END
GO

--10. NHACUNGCAP
CREATE TRIGGER TG_THEMTC_NHACC ON NHACUNGCAP
FOR INSERT
AS
BEGIN
    PRINT(N'THÊM NHÀ CUNG CẤP THÀNH CÔNG')
END
GO

--11. NHANVIEN
CREATE TRIGGER TG_THEMTC_NHANVIEN ON NHANVIEN
FOR INSERT 
AS
BEGIN
    PRINT(N'THÊM NHÂN VIÊN THÀNH CÔNG')
END
GO 

--12. TAIKHOANKH
CREATE TRIGGER TG_THEMTC_TAIKHOANKH ON TAIKHOANKH
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM TÀI KHOẢN KHÁCH HÀNG THÀNH CÔNG')
END
GO

--13. TAIKHOANNV
CREATE TRIGGER TG_THEMTC_TAIKHOANNV ON TAIKHOANNV
FOR INSERT
AS
BEGIN
    PRINT(N'THÊM TÀI KHOẢN NHÂN VIÊN THÀNH CÔNG')
END
GO

--14 TTSP
CREATE TRIGGER TG_THEMTC_TTSP ON TTSP
FOR INSERT
AS
BEGIN
    PRINT (N'THÊM TÌNH TRẠNG SẢN PHẨM THÀNH CÔNG')
END
GO

-- ĐIỀU KIỆN HỆ THỐNG -- 
CREATE TRIGGER TG_NKD_HANG ON HANG 
FOR INSERT
AS
BEGIN
    DECLARE @MATTSP NVARCHAR(10), @DONGIANHAP FLOAT
    SELECT @MATTSP = MATTSP, @DONGIANHAP = DONGIANHAP FROM inserted
    IF(@MATTSP = N'NKD' OR @DONGIANHAP <= 50000)
    BEGIN
        RAISERROR (N'ĐIỀU KIỆN NHẬP SAI',15,1)
        ROLLBACK TRAN
        RETURN 
    END
END